name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      cassandra:
        image: cassandra:4.1
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh -e 'describe cluster'" --health-interval 30s --health-timeout 10s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      
    - name: Install dependencies
      run: bun install
      
    - name: Build
      run: bun run build
      
    - name: Test
      run: bun test
